#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

echo "Cleaning simpleHIPFoam project..."

wclean src/hipAcceleration
wclean applications/solvers/simpleHIPFoam

echo "Clean complete!"
